import Projects from "../pages/projects/[id]";

const projectList = [
  {
    route: "richmond-road",
    name: "Richmond Road, Grey Lynn",
    url: "/projects/richmond-road",
    images: [
      {
        src: "/images/projects/richmond-road/Rarebirds interiors bespoke kitchen design, moroccan Tiles, CDK Oyster Stone Gaggenau appliances.jpg",
        name: "Rarebirds interiors bespoke kitchen design, moroccan Tiles, CDK Oyster Stone Gaggenau appliances.jpg",
        height: 1440,
        width: 1080,
        url: "/projects/richmond-road",
      },
      {
        src: "/images/projects/richmond-road/Rarebirds Interiors custom design kitchens, CDK oyster marble, Blanco sinks, Moroccan handmade tiles, Buddy brass kitchen mixer with spray, Tom Dixon.jpg",
        name: "Rarebirds Interiors custom design kitchens, CDK oyster marble, Blanco sinks, Moroccan handmade tiles, Buddy brass kitchen mixer with spray, Tom Dixon.jpg",
        height: 1440,
        width: 1080,
        url: "/projects/richmond-road",
      },
      {
        src: "/images/projects/richmond-road/Rarebirds Interiors laminated marble benchtop, CDK Oyster marble , solid Oak benctop, custom designed kitchens.jpg",
        name: "Rarebirds Interiors laminated marble benchtop, CDK Oyster marble , solid Oak benctop, custom designed kitchens.jpg",
        height: 1440,
        width: 1080,
        url: "/projects/richmond-road",
      },
      {
        src: "/images/projects/richmond-road/Rarebirds Interiors Luxury bathroom design, Progetto Japanese Soaking Tub, Catalano matt white toilet _ bidet.jpg",
        name: "Rarebirds Interiors Luxury bathroom design, Progetto Japanese Soaking Tub, Catalano matt white toilet _ bidet.jpg",
        height: 1440,
        width: 1080,
        url: "/projects/richmond-road",
      },
      {
        src: "/images/projects/richmond-road/Rarebirds Interiors luxury bathroom designs, rarebirds reeded glass shower screen, bespoke rarebirds vanity, nightworks code lights, Buddy white tapware, Progetto Japanese Soaking Tub.jpg",
        name: "Rarebirds Interiors luxury bathroom designs, rarebirds reeded glass shower screen, bespoke rarebirds vanity, nightworks code lights, Buddy white tapware, Progetto Japanese Soaking Tub.jpg",
        height: 1440,
        width: 1080,
        url: "/projects/richmond-road",
      },
      {
        src: "/images/projects/richmond-road/Rarebirds Interiors luxury bathrooms, Progetto Buddy white tapware Made of Tomorrow, Black Dahlia porcelain tiles.png",
        name: "Rarebirds Interiors luxury bathrooms, Progetto Buddy white tapware Made of Tomorrow, Black Dahlia porcelain tiles.png",
        height: 1645,
        width: 1080,
        url: "/projects/richmond-road",
      },
      {
        src: "/images/projects/richmond-road/Rarebirds Interiors luxury bathrooms, rarebirds reeded shower screen,  Nightworks code pendant lights, Buddy white tapware.jpg",
        name: "Rarebirds Interiors luxury bathrooms, rarebirds reeded shower screen,  Nightworks code pendant lights, Buddy white tapware.jpg",
        height: 1440,
        width: 1080,
        url: "/projects/richmond-road",
      },
      {
        src: "/images/projects/richmond-road/Rarebirds interiors luxury dining rooms ,feather lighting, rarebirds custom dining tableMokum handloom.jpg",
        name: "Rarebirds interiors luxury dining rooms ,feather lighting, rarebirds custom dining tableMokum handloom.jpg",
        height: 1440,
        width: 1080,
        url: "/projects/richmond-road",
      },
      {
        src: "/images/projects/richmond-road/Rarebirds Interiors luxury dining rooms.jpg",
        name: "Rarebirds Interiors luxury dining rooms.jpg",
        height: 1440,
        width: 1080,
        url: "/projects/richmond-road",
      },
      {
        src: "/images/projects/richmond-road/Rarebirds Interiors, Auckland Villa renovation, Artisan Bloom feather pendants, Orla Kiely Rugs, rarebirds furniture, Artful Curation, Aalto paints.jpg",
        name: "Rarebirds Interiors, Auckland Villa renovation, Artisan Bloom feather pendants, Orla Kiely Rugs, rarebirds furniture, Artful Curation, Aalto paints.jpg",
        height: 1440,
        width: 1080,
        url: "/projects/richmond-road",
      },
      {
        src: "/images/projects/richmond-road/Rarebirds Interiors, Black Dahlia porcelain tiles, Progetto Japanese Soaking Tub, Buddy White Bath mixers copy.jpg",
        name: "Rarebirds Interiors, Black Dahlia porcelain tiles, Progetto Japanese Soaking Tub, Buddy White Bath mixers copy.jpg",
        height: 1440,
        width: 1080,
        url: "/projects/richmond-road",
      },
      {
        src: "/images/projects/richmond-road/Rarebirds Interiors, customs doors, Artful Curation .jpg",
        name: "Rarebirds Interiors, customs doors, Artful Curation .jpg",
        height: 1440,
        width: 1080,
        url: "/projects/richmond-road",
      },
      {
        src: "/images/projects/richmond-road/RBI HQ  Kitchen with timber counter copy.jpg",
        name: "RBI HQ  Kitchen with timber counter copy.jpg",
        height: 1440,
        width: 1080,
        url: "/projects/richmond-road",
      },
    ],
  },
  {
    route: "benson-road",
    name: "Benson Road, Remuera",
    url: "/projects/benson-road",
    images: [
      {
        src: "/images/projects-small/benson-road/HERO SHOT - Rarebirds Interiors biophilic design bespoke kitchen design Gaggenau ovens CDK infinity brown granite.jpg",
        name: "HERO SHOT - Rarebirds Interiors biophilic design bespoke kitchen design Gaggenau ovens CDK infinity brown granite.jpg",
        height: 3245,
        width: 4868,
        url: "/projects/benson-road",
      },
      {
        src: "/images/projects-small/benson-road/Rarebirds Interiors bespoke benson birch cabinet design.jpg",
        name: "Rarebirds Interiors bespoke benson birch cabinet design.jpg",
        height: 2211,
        width: 3409,
        url: "/projects/benson-road",
      },
      {
        src: "/images/projects-small/benson-road/Rarebirds interiors bespoke kitchen design shelf lighting.jpg",
        name: "Rarebirds interiors bespoke kitchen design shelf lighting.jpg",
        height: 5178,
        width: 3840,
        url: "/projects/benson-road",
      },
      {
        src: "/images/projects-small/benson-road/Rarebirds interiors biophilic design bespoke kitchen cabinetry.jpg",
        name: "Rarebirds interiors biophilic design bespoke kitchen cabinetry.jpg",
        height: 3109,
        width: 5213,
        url: "/projects/benson-road",
      },
      {
        src: "/images/projects-small/benson-road/rarebirds interiors biophilic design twelfth night gin oak herringbone floor.jpg",
        name: "rarebirds interiors biophilic design twelfth night gin oak herringbone floor.jpg",
        height: 3840,
        width: 4380,
        url: "/projects/benson-road",
      },
      {
        src: "/images/projects-small/benson-road/rarebirds interiors custom designed kitchens.jpg",
        name: "rarebirds interiors custom designed kitchens.jpg",
        height: 2956,
        width: 3840,
        url: "/projects/benson-road",
      },
      {
        src: "/images/projects-small/benson-road/Rarebirds Interiors Infinity Brown Granite CDK Gaggenau appliances.jpg",
        name: "Rarebirds Interiors Infinity Brown Granite CDK Gaggenau appliances.jpg",
        height: 3584,
        width: 5341,
        url: "/projects/benson-road",
      },
      {
        src: "/images/projects-small/benson-road/Rarebirds Interiors kitchen storage Blum hardware Hafele pocket sliders shelf lighting Gaggenau ovens.jpg",
        name: "Rarebirds Interiors kitchen storage Blum hardware Hafele pocket sliders shelf lighting Gaggenau ovens.jpg",
        height: 4794,
        width: 3700,
        url: "/projects/benson-road",
      },
      {
        src: "/images/projects-small/benson-road/Rarebirds interiors Tim Webber stools herringbone tiles and oak floor infinity brown benchtop with herb planter Guggenau appliances.jpg",
        name: "Rarebirds interiors Tim Webber stools herringbone tiles and oak floor infinity brown benchtop with herb planter Guggenau appliances.jpg",
        height: 3126,
        width: 3696,
        url: "/projects/benson-road",
      },
      {
        src: "/images/projects-small/benson-road/Rarebirds interios dark oak kitchen Infinity brown granite benchtop .jpg",
        name: "Rarebirds interios dark oak kitchen Infinity brown granite benchtop .jpg",
        height: 3460,
        width: 5163,
        url: "/projects/benson-road",
      },
    ],
  },

  {
    route: "glenbush-place",
    name: "Glenbush Place, Birkenhead",
    url: "/projects/glenbush-place",
    images: [
      {
        src: "/images/projects-small/glenbush-place/RAREBIRDS INTERIORS CDK MYSTIQUE GREEN VANITY MODERN BATHROOM 013.jpg",
        name: "RAREBIRDS INTERIORS CDK MYSTIQUE GREEN VANITY MODERN BATHROOM 013.jpg",
        height: 2128,
        width: 4457,
        url: "/projects/glenbush-place",
      },
      {
        src: "/images/projects-small/glenbush-place/RAREBIRDS INTERIORS CONTEMPORARY KITCHEN WITH FINGER TILES 06.jpg",
        name: "RAREBIRDS INTERIORS CONTEMPORARY KITCHEN WITH FINGER TILES 06.jpg",
        height: 2996,
        width: 3264,
        url: "/projects/glenbush-place",
      },
      {
        src: "/images/projects-small/glenbush-place/RAREBIRDS INTERIORS MODERN AGED BRASS BUDDY BATHROOM 09.jpg",
        name: "RAREBIRDS INTERIORS MODERN AGED BRASS BUDDY BATHROOM 09.jpg",
        height: 5760,
        width: 3840,
        url: "/projects/glenbush-place",
      },
      {
        src: "/images/projects-small/glenbush-place/RAREBIRDS INTERIORS MODERN BUILT IN BATH BATHROOM 010.jpg",
        name: "RAREBIRDS INTERIORS MODERN BUILT IN BATH BATHROOM 010.jpg",
        height: 4864,
        width: 3223,
        url: "/projects/glenbush-place",
      },
      {
        src: "/images/projects-small/glenbush-place/RAREBIRDS INTERIORS MODERN FUMAO TILES BATHROOM 08.jpg",
        name: "RAREBIRDS INTERIORS MODERN FUMAO TILES BATHROOM 08.jpg",
        height: 2977,
        width: 4768,
        url: "/projects/glenbush-place",
      },
      {
        src: "/images/projects-small/glenbush-place/RAREBIRDS INTERIORS MODERN KITHCHEN WITH FINGER TILES 07.jpg",
        name: "RAREBIRDS INTERIORS MODERN KITHCHEN WITH FINGER TILES 07.jpg",
        height: 3219,
        width: 3219,
        url: "/projects/glenbush-place",
      },
      {
        src: "/images/projects-small/glenbush-place/RAREBIRDS INTERIORS MODERN KITHCHEN WITH TERRAZZO 05.jpg",
        name: "RAREBIRDS INTERIORS MODERN KITHCHEN WITH TERRAZZO 05.jpg",
        height: 3426,
        width: 5139,
        url: "/projects/glenbush-place",
      },
      {
        src: "/images/projects-small/glenbush-place/RAREBIRDS INTERIORS MODERN WHITE AND OAK VEENEER KITCHEN 02.jpg",
        name: "RAREBIRDS INTERIORS MODERN WHITE AND OAK VEENEER KITCHEN 02.jpg",
        height: 2827,
        width: 4637,
        url: "/projects/glenbush-place",
      },
      {
        src: "/images/projects-small/glenbush-place/RAREBIRDS INTERIORS TILED SHOWER ALCOVE LIGHTING BATHROOM 012.jpg",
        name: "RAREBIRDS INTERIORS TILED SHOWER ALCOVE LIGHTING BATHROOM 012.jpg",
        height: 5195,
        width: 3463,
        url: "/projects/glenbush-place",
      },
      {
        src: "/images/projects-small/glenbush-place/RAREBIRDS INTERIORS WALK IN BUDDY SHOWER MODERN BATHROOM 011.jpg",
        name: "RAREBIRDS INTERIORS WALK IN BUDDY SHOWER MODERN BATHROOM 011.jpg",
        height: 5361,
        width: 3751,
        url: "/projects/glenbush-place",
      },
      {
        src: "/images/projects-small/glenbush-place/RAREBIRDS INTERIORS WHITE AND OAK VENEER KITCHEN 01.jpg",
        name: "RAREBIRDS INTERIORS WHITE AND OAK VENEER KITCHEN 01.jpg",
        height: 3840,
        width: 5605,
        url: "/projects/glenbush-place",
      },
      {
        src: "/images/projects-small/glenbush-place/RAREBIRDS INTERIORS WHITE BOHO KITCHEN 03.jpg",
        name: "RAREBIRDS INTERIORS WHITE BOHO KITCHEN 03.jpg",
        height: 4906,
        width: 3674,
        url: "/projects/glenbush-place",
      },
      {
        src: "/images/projects-small/glenbush-place/RAREBIRDS INTERIORS WHITE KITCHEN WITH V GROOVE DETAIL 08.jpg",
        name: "RAREBIRDS INTERIORS WHITE KITCHEN WITH V GROOVE DETAIL 08.jpg",
        height: 5162,
        width: 3441,
        url: "/projects/glenbush-place",
      },
      {
        src: "/images/projects-small/glenbush-place/RAREBIRDS INTERIORS WHITE KTICHEN WITH SKYLIGHT 04.jpg",
        name: "RAREBIRDS INTERIORS WHITE KTICHEN WITH SKYLIGHT 04.jpg",
        height: 4452,
        width: 3840,
        url: "/projects/glenbush-place",
      },
    ],
  },
  {
    route: "jervois-road",
    name: "rarebirds interiors- poppy with little black dress",
    url: "/projects/jervois-road",
    images: [
      {
        src: "/images/projects-small/jervois-road/rarebirds interiors biophilic bathroom design brass heated towel poles stone bath bathroom plant wall.jpg",
        name: "rarebirds interiors biophilic bathroom design brass heated towel poles stone bath bathroom plant wall.jpg",
        height: 4868,
        width: 3840,
        url: "/projects/jervois-road",
      },
      {
        src: "/images/projects-small/jervois-road/Poppy grand piano and DG Dahlia fabric.jpg",
        name: "Poppy grand piano and DG Dahlia fabric.jpg",
        height: 2798,
        width: 2281,
        url: "/projects/jervois-road",
      },
      {
        src: "/images/projects-small/jervois-road/rarebirds interiors bathroom vanities reeded oak cabinetry capsule shaped mirrors.jpg",
        name: "rarebirds interiors bathroom vanities reeded oak cabinetry capsule shaped mirrors.jpg",
        height: 3015,
        width: 3949,
        url: "/projects/jervois-road",
      },

      {
        src: "/images/projects-small/jervois-road/rarebirds interiors luxury ensuite design reeded oak vanitystone basin  oak shower screen rarebirdsinteriors cabinet mirrors 2.jpg",
        name: "rarebirds interiors luxury ensuite design reeded oak vanitystone basin  oak shower screen rarebirdsinteriors cabinet mirrors 2.jpg",
        height: 4540,
        width: 3840,
        url: "/projects/jervois-road",
      },
      {
        src: "/images/projects-small/jervois-road/rarebirds interiors luxury ensuite design reeded oak vanitystone basin  oak shower screen rarebirdsinteriors cabinet mirrors.jpg",
        name: "rarebirds interiors luxury ensuite design reeded oak vanitystone basin  oak shower screen rarebirdsinteriors cabinet mirrors.jpg",
        height: 3840,
        width: 5272,
        url: "/projects/jervois-road",
      },
      {
        src: "/images/projects-small/jervois-road/rarebirds interiors nz bathroom plant wall oak shower screen brass bidet tap.jpg",
        name: "rarebirds interiors nz bathroom plant wall oak shower screen brass bidet tap.jpg",
        height: 5361,
        width: 3840,
        url: "/projects/jervois-road",
      },
      {
        src: "/images/projects-small/jervois-road/rarebirds interiors stylish bathroom design. fluted oak vanities portsea grey vanity top medicine cabinet Progetto brass tapware brass showe chanel.jpg",
        name: "rarebirds interiors stylish bathroom design. fluted oak vanities portsea grey vanity top medicine cabinet Progetto brass tapware brass showe chanel.jpg",
        height: 5361,
        width: 3186,
        url: "/projects/jervois-road",
      },
      {
        src: "/images/projects-small/jervois-road/rarebirds interiors stylish ensuite design moonstone tiles brass shower fittings fluted oak wallhung vanity.jpg",
        name: "rarebirds interiors stylish ensuite design moonstone tiles brass shower fittings fluted oak wallhung vanity.jpg",
        height: 4125,
        width: 2686,
        url: "/projects/jervois-road",
      },
      {
        src: "/images/projects-small/jervois-road/rarebirds interiors wall in shower design Progetto brass bathroom fitttings.jpg",
        name: "rarebirds interiors wall in shower design Progetto brass bathroom fitttings.jpg",
        height: 5145,
        width: 3430,
        url: "/projects/jervois-road",
      },
      {
        src: "/images/projects-small/jervois-road/rarebirds interiors- poppy with little black dress.jpg",
        name: "rarebirds interiors- poppy with little black dress.jpg",
        height: 2905,
        width: 2699,
        url: "/projects/jervois-road",
      },
    ],
  },
  {
    route: "omahu-road",
    name: "Omahu Road, Remuera",
    url: "/projects/omahu-road",
    images: [
      {
        src: "/images/projects-small/omahu-road/Singer-Remuera-19-Sean-High11.jpg",
        name: "Singer-Remuera-19-Sean-High11.jpg",
        height: 5760,
        width: 3840,
        url: "/projects/omahu-road",
      },
      {
        src: "/images/projects-small/omahu-road/Singer-Remuera-19-Sean-High13.jpg",
        name: "Singer-Remuera-19-Sean-High13.jpg",
        height: 5760,
        width: 3840,
        url: "/projects/omahu-road",
      },
      {
        src: "/images/projects-small/omahu-road/Singer-Remuera-19-Sean-High14.jpg",
        name: "Singer-Remuera-19-Sean-High14.jpg",
        height: 5760,
        width: 3840,
        url: "/projects/omahu-road",
      },
      {
        src: "/images/projects-small/omahu-road/Singer-Remuera-19-Sean-High32.jpg",
        name: "Singer-Remuera-19-Sean-High32.jpg",
        height: 3840,
        width: 5760,
        url: "/projects/omahu-road",
      },
      {
        src: "/images/projects-small/omahu-road/Singer-Remuera-19-Sean-High36.jpg",
        name: "Singer-Remuera-19-Sean-High36.jpg",
        height: 3840,
        width: 5760,
        url: "/projects/omahu-road",
      },
      {
        src: "/images/projects-small/omahu-road/Singer-Remuera-19-Sean-High37.jpg",
        name: "Singer-Remuera-19-Sean-High37.jpg",
        height: 3840,
        width: 5760,
        url: "/projects/omahu-road",
      },
      {
        src: "/images/projects-small/omahu-road/Singer-Remuera-19-Sean-High9.jpg",
        name: "Singer-Remuera-19-Sean-High9.jpg",
        height: 5760,
        width: 3840,
        url: "/projects/omahu-road",
      },
    ],
  },
  {
    route: "surrey-crescent",
    name: "Surrey Crescent, Grey Lynn",
    url: "/projects/surrey-crescent",
    images: [
      {
        src: "/images/projects-small/surrey-crescent/rarebirds interiors bathroom design  kohler dutch masters basin heated towel poles.jpg",
        name: "rarebirds interiors bathroom design  kohler dutch masters basin heated towel poles.jpg",
        height: 2284,
        width: 3223,
        url: "/projects/surrey-crescent",
      },
      {
        src: "/images/projects-small/surrey-crescent/rarebirds interiors feminine bathroom design Kohler dutch master basin LED bathroom artwork.jpg",
        name: "rarebirds interiors feminine bathroom design Kohler dutch master basin LED bathroom artwork.jpg",
        height: 3359,
        width: 4666,
        url: "/projects/surrey-crescent",
      },
      {
        src: "/images/projects-small/surrey-crescent/rarebirds interiors feminine small bathroom design rarebirds interiors LED artwork.jpg",
        name: "rarebirds interiors feminine small bathroom design rarebirds interiors LED artwork.jpg",
        height: 2929,
        width: 4056,
        url: "/projects/surrey-crescent",
      },
      {
        src: "/images/projects-small/surrey-crescent/rarebirds interiors LED bathroom artwork.jpg",
        name: "rarebirds interiors LED bathroom artwork.jpg",
        height: 1192,
        width: 1192,
        url: "/projects/surrey-crescent",
      },
    ],
  },
  {
    route: "hobson-street",
    name: "Hobson Street, Penthouse",
    url: "/projects/hobson-street",
    images: [
      {
        src: "/images/projects-small/hobson-street/Heritage-Hotel-20-Sean-High1.jpg",
        name: "Heritage-Hotel-20-Sean-High1.jpg",
        height: 5760,
        width: 3840,
        url: "/projects/hobson-street",
      },
      {
        src: "/images/projects-small/hobson-street/Heritage-Hotel-20-Sean-High34.jpg",
        name: "Heritage-Hotel-20-Sean-High34.jpg",
        height: 5760,
        width: 3840,
        url: "/projects/hobson-street",
      },
      {
        src: "/images/projects-small/hobson-street/Heritage-Hotel-20-Sean-High4.jpg",
        name: "Heritage-Hotel-20-Sean-High4.jpg",
        height: 3829,
        width: 5743,
        url: "/projects/hobson-street",
      },
      {
        src: "/images/projects-small/hobson-street/HERO SHOT- modern dark oak kitchen art deco penthouse appartment.jpg",
        name: "HERO SHOT- modern dark oak kitchen art deco penthouse appartment.jpg",
        height: 3840,
        width: 5760,
        url: "/projects/hobson-street",
      },
      {
        src: "/images/projects-small/hobson-street/rarebirds interiors black oak kitchen grand designs nz kitchen heritage hotel building.jpg",
        name: "rarebirds interiors black oak kitchen grand designs nz kitchen heritage hotel building.jpg",
        height: 3840,
        width: 5760,
        url: "/projects/hobson-street",
      },
      {
        src: "/images/projects-small/hobson-street/rarebirds interiors heritage hotel penthouse appartment modern dark oak kitchen miele ovens 2.jpg",
        name: "rarebirds interiors heritage hotel penthouse appartment modern dark oak kitchen miele ovens 2.jpg",
        height: 3840,
        width: 5760,
        url: "/projects/hobson-street",
      },
      {
        src: "/images/projects-small/hobson-street/rarebirds interiors heritage hotel penthouse appartment modern dark oak kitchen miele ovens.jpg",
        name: "rarebirds interiors heritage hotel penthouse appartment modern dark oak kitchen miele ovens.jpg",
        height: 5760,
        width: 3840,
        url: "/projects/hobson-street",
      },
      {
        src: "/images/projects-small/hobson-street/rarebirds interiors modern dark oak kitchen miele appaliances blanco sink pProgetto mixer CDK infinity black granite Heritage Hotel penthouse appartment.jpg",
        name: "rarebirds interiors modern dark oak kitchen miele appaliances blanco sink pProgetto mixer CDK infinity black granite Heritage Hotel penthouse appartment.jpg",
        height: 3840,
        width: 5760,
        url: "/projects/hobson-street",
      },
      {
        src: "/images/projects-small/hobson-street/rarebirds interiors modern dark stained oak kitchen- ghrand designs nz kitchen miele appliances.jpg",
        name: "rarebirds interiors modern dark stained oak kitchen- ghrand designs nz kitchen miele appliances.jpg",
        height: 3840,
        width: 5760,
        url: "/projects/hobson-street",
      },
    ],
  },
  {
    route: "westmere-crescent",
    name: "Westmere Crescent, Westmere",
    url: "/projects/westmere-crescent",
    images: [
      {
        src: "/images/projects/westmere-crescent/rarebirds interiors Elegant marblebathroom mother of pearl chandelier.jpg",
        name: "rarebirds interiors Elegant marblebathroom mother of pearl chandelier.jpg",
        height: 1152,
        width: 768,
        url: "/projects/westmere-crescent",
      },
      {
        src: "/images/projects/westmere-crescent/rarebirds interiors Bathroom laundry spanish handmade tiles kohler artisan basin purist mixer.jpg",
        name: "rarebirds interiors Bathroom laundry spanish handmade tiles kohler artisan basin purist mixer.jpg",
        height: 1152,
        width: 768,
        url: "/projects/westmere-crescent",
      },

      {
        src: "/images/projects/westmere-crescent/rarebirds interiors Laundry basin, Kohler Empress Bouquet basin Kohler Purist mixer.jpg",
        name: "rarebirds interiors Laundry basin, Kohler Empress Bouquet basin Kohler Purist mixer.jpg",
        height: 784,
        width: 768,
        url: "/projects/westmere-crescent",
      },
      {
        src: "/images/projects/westmere-crescent/rarebirds interiors laundry cupboard design Kohler empress basin purist mixer mallorca handmade tiles.jpg",
        name: "rarebirds interiors laundry cupboard design Kohler empress basin purist mixer mallorca handmade tiles.jpg",
        height: 768,
        width: 1012,
        url: "/projects/westmere-crescent",
      },
      {
        src: "/images/projects/westmere-crescent/rarebirds interiors Laundry cupboard mallorca tiles Kohler purist mixer KOhler Artisan Basin Ceasarstone Georgian Bluffs .jpg",
        name: "rarebirds interiors Laundry cupboard mallorca tiles Kohler purist mixer KOhler Artisan Basin Ceasarstone Georgian Bluffs .jpg",
        height: 768,
        width: 894,
        url: "/projects/westmere-crescent",
      },
      {
        src: "/images/projects/westmere-crescent/rarebirds interiors marble bathroom design kohler empress basin progetto swiss tapware rarebirds vanities.jpg",
        name: "rarebirds interiors marble bathroom design kohler empress basin progetto swiss tapware rarebirds vanities.jpg",
        height: 1309,
        width: 768,
        url: "/projects/westmere-crescent",
      },
      {
        src: "/images/projects/westmere-crescent/Rarebirds interiors Oak vanity mallorca tiles.jpg",
        name: "Rarebirds interiors Oak vanity mallorca tiles.jpg",
        height: 768,
        width: 1348,
        url: "/projects/westmere-crescent",
      },
      {
        src: "/images/projects/westmere-crescent/Rarebirds Oak vanity Ceasarstone Georgian Bluffs.jpg",
        name: "Rarebirds Oak vanity Ceasarstone Georgian Bluffs.jpg",
        height: 1021,
        width: 768,
        url: "/projects/westmere-crescent",
      },
      {
        src: "/images/projects-small/westmere-crescent/Rarebirds Oak vanity Ceasarstone Georgian Bluffs.jpg",
        name: "Rarebirds Oak vanity Ceasarstone Georgian Bluffs.jpg",
        height: 4131,
        width: 3107,
        url: "/projects/westmere-crescent",
      },
    ],
  },
  {
    route: "wainui-road",
    name: "Wainui Road, Raglan",
    url: "/projects/wainui-road",
    images: [
      {
        src: "/images/projects/wainui-road/HERO SHOT - RAREBIRDS INTERIORS BEACH KTICHEN HANDLESS TONGUE AND GROOVE CABINETRY 01.jpg",
        project: "wainui-road",
        file: "HERO SHOT - RAREBIRDS INTERIORS BEACH KTICHEN HANDLESS TONGUE AND GROOVE CABINETRY 01.jpg",
        height: 1071,
        width: 1620,
        url: "/projects/wainui-road",
      },
      {
        src: "/images/projects/wainui-road/RAREBIRDS INTERIORS WHITE GROVE AND DARK VENEER BLUM LEGRABOX DRAWERS 09.jpg",
        project: "wainui-road",
        file: "RAREBIRDS INTERIORS WHITE GROVE AND DARK VENEER BLUM LEGRABOX DRAWERS 09.jpg",
        height: 1080,
        width: 1080,
        url: "/projects/wainui-road",
      },
      {
        src: "/images/projects/wainui-road/RAREBIRDS CUSTOM KITCHEN DESIGN BOSCH INTEGRATED DISHWASHER HANDLESS KITCHEN 07.jpg",
        project: "wainui-road",
        file: "RAREBIRDS CUSTOM KITCHEN DESIGN BOSCH INTEGRATED DISHWASHER HANDLESS KITCHEN 07.jpg",
        height: 1620,
        width: 1080,
        url: "/projects/wainui-road",
      },
      {
        src: "/images/projects/wainui-road/RAREBIRDS HANDLESS KITCHEN CORNER DETAIL ALTO AND VENEER 06.jpg",
        project: "wainui-road",
        file: "RAREBIRDS HANDLESS KITCHEN CORNER DETAIL ALTO AND VENEER 06.jpg",
        height: 1080,
        width: 1080,
        url: "/projects/wainui-road",
      },
      {
        src: "/images/projects/wainui-road/RAREBIRDS INTERIORS BEACH KITCHEN CUSTOMER BUILT EXTRACTION CANOPY SHELF LIGHTIING 03.jpg",
        project: "wainui-road",
        file: "RAREBIRDS INTERIORS BEACH KITCHEN CUSTOMER BUILT EXTRACTION CANOPY SHELF LIGHTIING 03.jpg",
        height: 1080,
        width: 1620,
        url: "/projects/wainui-road",
      },
      {
        src: "/images/projects/wainui-road/RAREBIRDS INTERIORS BEACH KITCHEN DESIGN GROOVED DRAWER FRONTS FLOATING SHELVES 08-.jpg",
        project: "wainui-road",
        file: "RAREBIRDS INTERIORS BEACH KITCHEN DESIGN GROOVED DRAWER FRONTS FLOATING SHELVES 08-.jpg",
        height: 1580,
        width: 1080,
        url: "/projects/wainui-road",
      },
      {
        src: "/images/projects/wainui-road/RAREBIRDS INTERIORS MODERN BEACH KITCHEN BOSCH APPLIANCES 04.jpg",
        project: "wainui-road",
        file: "RAREBIRDS INTERIORS MODERN BEACH KITCHEN BOSCH APPLIANCES 04.jpg",
        height: 1080,
        width: 1471,
        url: "/projects/wainui-road",
      },
      {
        src: "/images/projects/wainui-road/RAREBIRDS INTERIORS PLUMBLINE CHROME MIXER 02.jpg",
        project: "wainui-road",
        file: "RAREBIRDS INTERIORS PLUMBLINE CHROME MIXER 02.jpg",
        height: 1505,
        width: 1080,
        url: "/projects/wainui-road",
      },
      {
        src: "/images/projects/wainui-road/RAREBIRDS INTERIORS SIT AT KITCHEN ISLAND TIMBER ISLAND ALTO PAINTS 05.jpg",
        project: "wainui-road",
        file: "RAREBIRDS INTERIORS SIT AT KITCHEN ISLAND TIMBER ISLAND ALTO PAINTS 05.jpg",
        height: 1266,
        width: 1080,
        url: "/projects/wainui-road",
      },
      {
        src: "/images/projects/wainui-road/RAREBIRDS SCULLERY WITH LAUNDRY DARK VENEER STAINED OAK SHELVES 010.jpg",
        project: "wainui-road",
        file: "RAREBIRDS SCULLERY WITH LAUNDRY DARK VENEER STAINED OAK SHELVES 010.jpg",
        height: 1620,
        width: 1080,
        url: "/projects/wainui-road",
      },
    ],
  },

  {
    route: "riddel-road",
    name: "Riddel Road, Glendowie",
    url: "/projects/riddel-road",
    images: [
      {
        src: "/images/projects-small/riddel-road/4J2A2544.jpg",
        name: "4J2A2544.jpg",
        height: 3001,
        width: 4500,
        url: "/projects/riddel-road",
      },
      {
        src: "/images/projects-small/riddel-road/4J2A2561.jpg",
        name: "4J2A2561.jpg",
        height: 2999,
        width: 4500,
        url: "/projects/riddel-road",
      },
      {
        src: "/images/projects-small/riddel-road/4J2A3150.jpg",
        name: "4J2A3150.jpg",
        height: 3001,
        width: 4500,
        url: "/projects/riddel-road",
      },
      {
        src: "/images/projects-small/riddel-road/4J2A3267.jpg",
        name: "4J2A3267.jpg",
        height: 3000,
        width: 4500,
        url: "/projects/riddel-road",
      },
      {
        src: "/images/projects-small/riddel-road/RAREBIRDS INTERIORS CONTEMPORARY BLACK AND BROWN KTICHEN 05.jpg",
        name: "RAREBIRDS INTERIORS CONTEMPORARY BLACK AND BROWN KTICHEN 05.jpg",
        height: 3000,
        width: 4500,
        url: "/projects/riddel-road",
      },
      {
        src: "/images/projects-small/riddel-road/RAREBIRDS INTERIORS CONTEMPORARY KTICHEN TIMBER FLOOR 09.jpg",
        name: "RAREBIRDS INTERIORS CONTEMPORARY KTICHEN TIMBER FLOOR 09.jpg",
        height: 3016,
        width: 4506,
        url: "/projects/riddel-road",
      },
      {
        src: "/images/projects-small/riddel-road/RAREBIRDS INTERIORS DARK MARQUINA KITCHEN WITH MIELE 08.jpg",
        name: "RAREBIRDS INTERIORS DARK MARQUINA KITCHEN WITH MIELE 08.jpg",
        height: 3006,
        width: 4503,
        url: "/projects/riddel-road",
      },
    ],
  },
  {
    route: "kings-street",
    name: "Kings Street, Kingsland",
    url: "/projects/kings-street",
    images: [
      {
        src: "/images/projects/kings-street/RAREBIRDS INTERIORS RETRO AND RIMU KITCHEN 01.jpg",
        name: "RAREBIRDS INTERIORS RETRO AND RIMU KITCHEN 01.jpg",
        height: 768,
        width: 1130,
        url: "/projects/kings-street",
      },
      {
        src: "/images/projects/kings-street/RAREBIRDS INTERIORS RETRO RIMU KTICHEN 04.jpg",
        name: "RAREBIRDS INTERIORS RETRO RIMU KTICHEN 04.jpg",
        height: 735,
        width: 1152,
        url: "/projects/kings-street",
      },
      {
        src: "/images/projects/kings-street/RAREBIRDS INTERIORS RETRO SMEG KITCHEN 03.jpg",
        name: "RAREBIRDS INTERIORS RETRO SMEG KITCHEN 03.jpg",
        height: 1152,
        width: 768,
        url: "/projects/kings-street",
      },
      {
        src: "/images/projects/kings-street/RAREBIRDS INTERIORS RETRO SMEG KTICHEN METAL SHELVES .jpg",
        name: "RAREBIRDS INTERIORS RETRO SMEG KTICHEN METAL SHELVES .jpg",
        height: 1152,
        width: 706,
        url: "/projects/kings-street",
      },
      {
        src: "/images/projects/kings-street/RAREBIRDS INTERIORS VINTAGE LOOK KITCHEN 02 .jpg",
        name: "RAREBIRDS INTERIORS VINTAGE LOOK KITCHEN 02 .jpg",
        height: 768,
        width: 1152,
        url: "/projects/kings-street",
      },
      {
        src: "/images/projects/kings-street/RAREBIRDS INTERIORS CUSTOMER RIMU KITCHEN 05.jpg",
        name: "RAREBIRDS INTERIORS CUSTOMER RIMU KITCHEN 05.jpg",
        height: 1152,
        width: 768,
        url: "/projects/kings-street",
      },
    ],
  },
];

export default projectList;
